version: "3"

services:
  app:
    image: bitnami/laravel:latest
    volumes:
      - ./src:/app
    environment:
      - REDIS_HOST="redis"
    ports:
      - 8006:8000
  worker1:
    image: bitnami/laravel:latest
    command: php artisan queue:work
    volumes:
      - ./src:/app
    environment:
      - REDIS_HOST="redis"
  worker2:
    image: bitnami/laravel:latest
    command: php artisan queue:work
    volumes:
      - ./src:/app
    environment:
      - REDIS_HOST="redis"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobtest
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    privileged: true